#!/usr/bin/env bash

#shellcheck source=helper.sh
source ~/bin/helper.sh
#shellcheck source=helper-funcs.sh
source ~/bin/helper-funcs.sh

# decide whether this is appropriate:
set -e

debug_var command_base

# while [ $# -gt 0 ]; do
#    (
#       thinbanner "$1" >/dev/stderr
#       thes.pl "$1"
#    ) | column -x -c $((COLUMNS / 2)) | less

#    shift
# done

while [ $# -gt 0 ]; do

   words=()
   unset header

   "$command_dir/thes.pl" $1 | tr -d '\r' | sed -E 's/[[:space:]][[:space:]]+/\t/g' |
      while read -r output_line; do

         # if [[ "$output_line" == "***"* ]]; then
         #     warn "$output_line"
         #     break
         # elif [[ "$output_line" == *"..." ]]; then
         #     info "$output_line"
         #     continue
         # fi

         # output_line="${output_line}"
         # output_line="${output_line//,/}"

         preIFS="$IFS"
         IFS=$'\t'
         output_words=($output_line)
         IFS="$preIFS"

         if [ ${#output_words[@]} -eq 1 ]; then
            if [ "${#words}" -gt 0 ]; then
               if [ -n "$header" ]; then
                  thinbanner "${header^^}"
               fi
               printf '%s\n' "${words[@]}" | column -x -c $((COLUMNS - 1))
            fi

            header="${output_words[0]}"
            words=()

         else
            for word in "${output_words[@]}"; do
               words+=("${word}")
            done
         fi

      done | less

   shift
done

#     rhyme "$1" |
#         tr ',' '\n' |
#         sed -E 's/^([0-9]+):/---\1---\n/g' |
#         bat
#     shift
# done
