#!/usr/bin/env bash

#shellcheck source=../.qfuncs.sh
. ~/.qfuncs.sh

# decide whether this is appropriate:
set -e

# if command -v bat >/dev/null 2>&1; then
#    pager=bat
# else
#    pager=less
# fi

# if [[ $1 =~ ^--?c(ols)?$ ]]; then
#    colpipe=true
#    shift
# else
#    colpipe=false
# fi

cd "$(dirname "$(realpath "$0")")" || die

# words=()
# read -r cols < <(tput cols)
# unset header

# mapfile words < <(./thes.pl "$1")

./thes.pl "$1"

# osascript <<EOM
# set longText to "${words[@]}"
# set dialogText to "
#     <html>
#         <body>
#             <p style='width: 300px; height: 200px; overflow: scroll; white-space: pre-wrap;'>" & longText & "</p>
#         </body>
#     </html>
# "
# display dialog dialogText as text with title "Scrollable Text" buttons {"OK"}
# EOM
